- hosts: lb
  tasks:
  - name: Install haproxy package
    ansible.builtin.package:
        name: haproxy
        state: present

  - name: update configuration for haproxy
    ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

  - name: start haproxy service
    ansible.builtin.service:
        name: haproxy
        state: started
        enabled: yes

- hosts: webservers
  tasks:
  - name: install webserver package
    ansible.builtin.package:
        name: httpd
        state: present

  - name: update web page
    ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html

  - name: start webserver service
    ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
