- hosts: localhost
  vars:
    web_package: "httpd"
    web_content: "Web page from Variable PB"
    document_root: "/var/www/html"
  tasks:
  - name: Install webserver package
    ansible.builtin.package:
        name: "{{ web_package }}"
        state: present

  - name: create web page
    ansible.builtin.copy:
        content: "{{ web_content }}"
        dest: "{{document_root }}/index.html"

  - name: start service of webserver
    ansible.builtin.service:
        name: "{{ web_package }}"
        state: started
        enabled: yes
