- hosts: localhost
  vars:
    server_name: example.com
    backend_servers:
      - 192.168.1.10
      - 192.168.1.11
    ssl_enabled: true
  tasks:
    - name: Generate Nginx configuration with SSL
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
